<?php include __DIR__.'/inc/header.phtml'; ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="jumbotron">
                <?php if (null === $this->uri): ?>
        	        <h1>Error <small><em>Fizz</em><strong>Buzz</strong></small></h1>
                	<p>Sorry, unknown system error happened.</p>
            	<?php else: ?>
        	        <h1>404 <small><em>Fizz</em><strong>Buzz</strong></small></h1>
    	           	<p>The resource you are looking for could not be found.</p>
	               	<p>uri attempted:<?= htmlentities($this->uri)?></p>
               	 <?php endif;?>
            </div>
        </div>
    </div>
</div>

<?php include __DIR__.'/inc/footer.phtml'; ?>
